In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('C:/Users/gram/Documents/카카오톡 받은 파일/dataset.csv', index_col=0)
df

sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
age                                                                          
63     1   3       145   233    1        0      150      0      2.3      0   
37     1   2       130   250    0        1      187      0      3.5      0   
41     0   1       130   204    0        0      172      0      1.4      2   
56     1   1       120   236    0        1      178      0      0.8      2   
57     0   0       120   354    0        1      163      1      0.6      2   
..   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...   
57     0   0       140   241    0        1      123      1      0.2      1   
45     1   3       110   264    0        1      132      0      1.2      1   
68     1   0       144   193    1        1      141      0      3.4      1   
57     1   0       130   131    0        1      115      1      1.2      1   
57     0   1       130   236    0        0      174      0      0.0      1   

     ca  thal  target  
age                    
63    0     1       1  
37    0     2       1  
41    0     2       1  
56    0     2       1  
57    0     2       1  
..   ..   ...     ...  
57    0     3       0  
45    0     3       0  
68    2     3       0  
57    1     3       0  
57    1     2       0  

[303 rows x 13 columns]

In [11]:
df.keys()

Index(['sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang',
       'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [12]:
df_data = df.iloc[:, 1:5]
df_target = df.iloc[:,5]

In [14]:
df_target

target
age        
63        1
37        1
41        1
56        1
57        1
..      ...
57        0
45        0
68        0
57        0
57        0

[303 rows x 1 columns]

In [15]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 303 entries, 63 to 57
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cp        303 non-null    int64
 1   trestbps  303 non-null    int64
 2   chol      303 non-null    int64
 3   fbs       303 non-null    int64
dtypes: int64(4)
memory usage: 11.8 KB


In [17]:
y = df['target']
x = df_data
y

age
63    1
37    1
41    1
56    1
57    1
     ..
57    0
45    0
68    0
57    0
57    0
Name: target, Length: 303, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [19]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.5657894736842105
[[ 0 33]
 [ 0 43]]


In [20]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.6710526315789473
[[21 12]
 [13 30]]


In [21]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.7631578947368421
[[25  8]
 [10 33]]


In [22]:
# RF

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.7763157894736842
[[24  9]
 [ 8 35]]
